---
abstract: 'Smart matching utilities'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.021
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Smart-Match
requires:
  Carp: 0
  List::MoreUtils: 0
  Scalar::Util: 0
  Sub::Exporter::Progressive: 0
  XSLoader: 0
  constant: 0
  experimental: 0
  overload: 0
  perl: 5.010001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Smart-Match
  repository: git://github.com/Leont/smart-match.git
version: 0.007
